### ISSUE TITLE
Change Password throws "Password incorrect" but password got changed 

### ISSUE THREAD

**Issue by hoanglambatcoc** [IBM/JTOpen#136]
We found that the com.ibm.as400.access.AS400ImplRemote.changePassword is not working as before. The password gets changed but sign on triggered inside changePassword function returns error “Password incorrect”. 
This issue stated happening the PTF upgrade and issue also occurs on customer sites too

Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:656 BST 2023  Password change implementation successful.
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:656 BST 2023  CredentialVault(byte[] credential) called
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:656 BST 2023  CredentialVault.storedEncodedUsingExternalSeeds called
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:656 BST 2023  CredentialVault.getClearCredential called
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:656 BST 2023  CredentialVault.disposeOfCredential called
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:656 BST 2023  CredentialVault.storedEncodedUsingInternalSeeds called
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:657 BST 2023  Current userID in EBCDIC: 
D7 C1 E7 E6 C5 C2 40 40 40 40 
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:657 BST 2023  Current userID: 'PAXWEB'
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:657 BST 2023  CredentialVault.getClearCredential called
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:666 BST 2023  [com.ibm.as400.access.BidiConversionProperties@67bdddb8:Constructing](mailto:com.ibm.as400.access.BidiConversionProperties@67bdddb8:Constructing) BidiConversionProperties.
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:666 BST 2023  Converting byte array to string for ccsid: 37 offset:12 len:7
C3 D7 C6 F2 F2 C5 F2 
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:666 BST 2023  Destination string for ccsid: 37
00 43 00 50 00 46 00 32 00 32 00 45 00 32 
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:666 BST 2023  Change password failed:
com.ibm.as400.access.AS400SecurityException: Password is incorrect.:BGTEST3
                at com.ibm.as400.access.AS400ImplRemote.mapNativeSecurityException(AS400ImplRemote.java:3766)
                at com.ibm.as400.access.AS400ImplRemote.swapTo(AS400ImplRemote.java:3732)
                at com.ibm.as400.access.AS400ImplRemote.signon(AS400ImplRemote.java:3366)
                at com.ibm.as400.access.AS400ImplRemote.signon2(AS400ImplRemote.java:3318)
                at com.ibm.as400.access.AS400ImplRemote.changePassword(AS400ImplRemote.java:560)
                at com.ibm.as400.access.AS400.changePassword(AS400.java:1383)
                at com.cscfsg.msp.processors.ExitPointToolbox.processChangePassword(Unknown Source)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
                at java.lang.reflect.Method.invoke(Method.java:508)
                at com.cscfsg.msp.processors.ExitPointToolbox.process(Unknown Source)
                at com.cscfsg.msp.core.Worker.runDirect(Unknown Source)
                at com.cscfsg.msp.core.Worker.run(Unknown Source)
                at com.cscfsg.msp.core.WorkerThread.run(Unknown Source)
Thread[Thread-179,5,main]  Wed Oct 25 09:34:13:676 BST 2023  Calling NativeMethods.socketPaseClose(394)

[ToolboxTracePasswordChange.txt](https://github.com/IBM/JTOpen/files/13185537/ToolboxTracePasswordChange.txt)

Full Toolbox trace log

**Comment by ThePrez** [comment]
I am unable to recreate this issue with the latest version, so this may already be fixed. Can you evaluate with version 20.0.3? (simply backup the existing `/QIBM/ProdData/OS400/jt400/lib/jt400Native.jar` and replace it with the `jt400-20.0.3-native.jar` from the download)

**Comment by hoanglambatcoc** [comment]
Thanks, Change Password works fine with Toobox 20.0.3
