### ISSUE TITLE
Connections to DDM server fail with exclamation point in the password

### ISSUE THREAD

**Issue by ThePrez** [IBM/JTOpen#14]
If the user's password contains an exclamation point (`!`), connections to DDM (`AS400.RECORDACCESS`) may fail, manifesting in exceptions similar to the following examples:

```fortran
java.lang.Exception: Character UX'21' is not valid.
       at com.ibm.as400.access.SignonConverter.stringToByteArray(SignonConverter.java:214)
```

```fortran
Exception in thread "main" com.ibm.as400.access.AS400SecurityException: Password is incorrect.:USEREX
        at com.ibm.as400.access.AS400ImplRemote.returnSecurityException(AS400ImplRemote.java:3107)
        at com.ibm.as400.access.AS400ImplRemote.signon(AS400ImplRemote.java:3437)
```

**Comment by ThePrez** [comment]
A simple testcase:
```java
AS400 as400 = new AS400("systemname", "USRPRF", "password!".toCharArray());
as400.setGuiAvailable(false);
as400.connectService(AS400.RECORDACCESS);
as400.disconnectAllServices();
System.out.println("Success!");
```
