### ISSUE TITLE
Internal Driver Error : Invalid data type from server

### ISSUE THREAD

**Issue by RMcGennity** [IBM/JTOpen#193]
We are experiencing an internal driver error while executing a statement using the following version

<dependency>
<groupId>net.sf.jt400</groupId>
<artifactId>jt400</artifactId>
<version>20.0.7</version>
<classifier>java11</classifier>
</dependency>

Caused by: java.sql.SQLException: Internal driver error. (54210)
    at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:985)
    at com.ibm.as400.access.JDError.throwSQLException(JDError.java:610)
    at com.ibm.as400.access.JDError.throwSQLException(JDError.java:568)
    at com.ibm.as400.access.JDError.throwSQLException(JDError.java:491)
    at com.ibm.as400.access.SQLDataFactory.newData(SQLDataFactory.java:585)
    at com.ibm.as400.access.SQLDataFactory.newData(SQLDataFactory.java:559)
    at com.ibm.as400.access.JDServerRow.initialize(JDServerRow.java:239)
    at com.ibm.as400.access.JDServerRow.<init>(JDServerRow.java:80)
    at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1825)
    at com.ibm.as400.access.AS400JDBCPreparedStatementImpl.<init>(AS400JDBCPreparedStatementImpl.java:357)
    at com.ibm.as400.access.AS400JDBCConnectionImpl.prepareStatement(AS400JDBCConnectionImpl.java:2313)
    at com.ibm.as400.access.AS400JDBCConnectionImpl.prepareStatement(AS400JDBCConnectionImpl.java:2084)
    at com.ibm.as400.access.AS400JDBCConnectionImpl.prepareStatement(AS400JDBCConnectionImpl.java:2079)
    at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
    at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
    at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
    at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
    at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
    at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by jeber-ibm** [comment]
Can you collect a JTOpen trace and post it? It looks like the server is returning an invalid data type.

**Comment by jeber-ibm** [comment]
Closing until additional information available.
