### ISSUE TITLE
JDBC Connection Login timeout error with jt400-20.0.7-java11.jar 

### ISSUE THREAD

**Issue by sreedhar51** [IBM/JTOpen#196]
Hello!

We got this connection timeout error with the latest 20.0.7 JT Open driver on Java 11 environment.
It seems its related to this Java class in the package - https://github.com/piguangming/jt400/blob/master/src/com/ibm/as400/access/ClientAccessDataStream.java.

Please check and let us know how to resolve this error.

**Error stack trace:**

JobCourier0  Mon Aug 19 11:26:54:978 CDT 2024  as400: Driver AS/400 Toolbox for Java JDBC Driver (1799492991) : Using IBM Toolbox for Java JDBC driver implementation.
JobCourier0  Mon Aug 19 11:26:54:979 CDT 2024  Getting system property: 'com.ibm.as400.access.AS400.proxyServer'
JobCourier0  Mon Aug 19 11:26:54:979 CDT 2024  Value found in system properties:  'null'
JobCourier0  Mon Aug 19 11:26:54:979 CDT 2024  Value found in jt400.properties file: 'null'
JobCourier0  Mon Aug 19 11:26:54:979 CDT 2024  Value not found.
JobCourier0  Mon Aug 19 11:26:54:979 CDT 2024  CredentialVault.getClearCredential called
JobCourier0  Mon Aug 19 11:26:54:980 CDT 2024  Getting system property: 'com.ibm.as400.access.JDBC.secureCurrentUser'
JobCourier0  Mon Aug 19 11:26:54:980 CDT 2024  Value found in system properties:  'null'
JobCourier0  Mon Aug 19 11:26:54:980 CDT 2024  Value found in jt400.properties file: 'null'
JobCourier0  Mon Aug 19 11:26:54:980 CDT 2024  Value not found.
JobCourier0  Mon Aug 19 11:26:54:982 CDT 2024  Getting NLV.
JobCourier0  Mon Aug 19 11:26:54:983 CDT 2024  NLV Locale: en_US
JobCourier0  Mon Aug 19 11:26:54:986 CDT 2024  NLV for Locale: en, NLV: 2924
JobCourier0  Mon Aug 19 11:26:54:991 CDT 2024  Constructing AS400 object, system name: 'SYS01.repsrv.com' user ID: 'EAIUATUSR'
JobCourier0  Mon Aug 19 11:26:54:991 CDT 2024  CredentialVault(byte[] credential) called
JobCourier0  Mon Aug 19 11:26:54:992 CDT 2024  Getting system property: 'com.ibm.as400.access.AS400.proxyServer'
JobCourier0  Mon Aug 19 11:26:54:992 CDT 2024  Value found in system properties:  'null'
JobCourier0  Mon Aug 19 11:26:54:992 CDT 2024  Value found in jt400.properties file: 'null'
JobCourier0  Mon Aug 19 11:26:54:992 CDT 2024  Value not found.
JobCourier0  Mon Aug 19 11:26:54:996 CDT 2024  Setting GUI available:  false
JobCourier0  Mon Aug 19 11:26:54:997 CDT 2024  Checking if properties are frozen:  false
JobCourier0  Mon Aug 19 11:26:54:997 CDT 2024  Getting socket properties.
JobCourier0  Mon Aug 19 11:26:54:998 CDT 2024  Setting socket login timeout:  0
JobCourier0  Mon Aug 19 11:26:54:998 CDT 2024  Setting socket properties: com.ibm.as400.access.SocketProperties@63
JobCourier0  Mon Aug 19 11:26:54:999 CDT 2024  Checking for multiple Toolbox versions.
JobCourier0  Mon Aug 19 11:26:55:032 CDT 2024  Constructing conversion table for ccsid/encoding: 13488/Unicode
JobCourier0  Mon Aug 19 11:26:55:037 CDT 2024  Getting system property: 'com.ibm.as400.access.noDBReplyPooling'
JobCourier0  Mon Aug 19 11:26:55:037 CDT 2024  Value found in system properties:  'null'
JobCourier0  Mon Aug 19 11:26:55:038 CDT 2024  Value found in jt400.properties file: 'null'
JobCourier0  Mon Aug 19 11:26:55:038 CDT 2024  Value not found.
JobCourier0  Mon Aug 19 11:26:55:038 CDT 2024  Getting system property: 'com.ibm.as400.access.DBDSPool.monitor'
JobCourier0  Mon Aug 19 11:26:55:038 CDT 2024  Value found in system properties:  'null'
JobCourier0  Mon Aug 19 11:26:55:038 CDT 2024  Value found in jt400.properties file: 'null'
JobCourier0  Mon Aug 19 11:26:55:038 CDT 2024  Value not found.
JobCourier0  Mon Aug 19 11:26:55:043 CDT 2024  Path of AS400 class:  file:/C:/temp/jt400/jt400.jar!/com/ibm/as400/access/AS400.class
JobCourier0  Mon Aug 19 11:26:55:043 CDT 2024  Path of loaded impl class:  file:/C:/temp/jt400/jt400.jar!/com/ibm/as400/access/AS400JDBCConnectionImpl.class
JobCourier0  Mon Aug 19 11:26:55:047 CDT 2024  Connecting service:  4
JobCourier0  Mon Aug 19 11:26:55:047 CDT 2024  Checking for multiple Toolbox versions.
JobCourier0  Mon Aug 19 11:26:55:071 CDT 2024  Class com.ibm.as400.access.AS400ImplRemote was loaded from file:/C:/temp/jt400/jt400.jar!/com/ibm/as400/access/AS400ImplRemote.class
JobCourier0  Mon Aug 19 11:26:55:072 CDT 2024  Path of AS400 class:  file:/C:/temp/jt400/jt400.jar!/com/ibm/as400/access/AS400.class
JobCourier0  Mon Aug 19 11:26:55:073 CDT 2024  Path of loaded impl class:  file:/C:/temp/jt400/jt400.jar!/com/ibm/as400/access/AS400ImplRemote.class
JobCourier0  Mon Aug 19 11:26:55:073 CDT 2024  CredentialVault(byte[] credential) called
JobCourier0  Mon Aug 19 11:26:55:073 CDT 2024  Not using native optimizations. Reason follows:
JobCourier0  Mon Aug 19 11:26:55:073 CDT 2024    onAS400:  false
JobCourier0  Mon Aug 19 11:26:55:074 CDT 2024    systemNameLocal:  false
JobCourier0  Mon Aug 19 11:26:55:076 CDT 2024  Not using native optimizations; class 'NativeVersion' is not found.
JobCourier0  Mon Aug 19 11:26:55:076 CDT 2024    nativeVersion:  0
JobCourier0  Mon Aug 19 11:26:55:077 CDT 2024  Setting up AS400 implementation object:
JobCourier0  Mon Aug 19 11:26:55:078 CDT 2024    Enable SSL connections: null
JobCourier0  Mon Aug 19 11:26:55:078 CDT 2024    Native optimizations allowed:  false
JobCourier0  Mon Aug 19 11:26:55:078 CDT 2024    Use threaded communications:  true
JobCourier0  Mon Aug 19 11:26:55:079 CDT 2024    User specified CCSID:  0
JobCourier0  Mon Aug 19 11:26:55:079 CDT 2024    NLV:  2924
JobCourier0  Mon Aug 19 11:26:55:079 CDT 2024    Socket properties: com.ibm.as400.access.SocketProperties@63
JobCourier0  Mon Aug 19 11:26:55:080 CDT 2024    DDM RDB:  (null)
JobCourier0  Mon Aug 19 11:26:55:080 CDT 2024    Must use net sockets:  false
JobCourier0  Mon Aug 19 11:26:55:080 CDT 2024    Must use supplied profile:  false
JobCourier0  Mon Aug 19 11:26:55:080 CDT 2024    Must add language library:  false
JobCourier0  Mon Aug 19 11:26:55:081 CDT 2024  User ID: 'EAIUATUSR'
JobCourier0  Mon Aug 19 11:26:55:081 CDT 2024  Validate security...
JobCourier0  Mon Aug 19 11:26:55:082 CDT 2024  Signing-on without prompting...
JobCourier0  Mon Aug 19 11:26:55:082 CDT 2024  CredentialVault clone called
JobCourier0  Mon Aug 19 11:26:55:082 CDT 2024  CredentialVault.storedEncodedUsingExternalSeeds called
JobCourier0  Mon Aug 19 11:26:55:082 CDT 2024  CredentialVault.getClearCredential called
JobCourier0  Mon Aug 19 11:26:55:082 CDT 2024  CredentialVault.disposeOfCredential called
JobCourier0  Mon Aug 19 11:26:55:083 CDT 2024  CredentialVault.storedEncodedUsingInternalSeeds called
JobCourier0  Mon Aug 19 11:26:55:083 CDT 2024  Read security validation reply...
JobCourier0  Mon Aug 19 11:26:55:083 CDT 2024  Security validated successfully.
JobCourier0  Mon Aug 19 11:26:55:085 CDT 2024  Signon server reports CCSID:  37
JobCourier0  Mon Aug 19 11:26:55:090 CDT 2024  Class com.ibm.as400.access.NLS was loaded from file:/C:/temp/jt400/jt400.jar!/com/ibm/as400/access/NLS.class
JobCourier0  Mon Aug 19 11:26:55:092 CDT 2024  Constructing conversion table for ccsid/encoding: 37/Cp037
JobCourier0  Mon Aug 19 11:26:55:093 CDT 2024  Decompressing single-byte conversion table for ccsid: 37  131
JobCourier0  Mon Aug 19 11:26:55:095 CDT 2024  Successfully loaded single-byte map for ccsid: 37
JobCourier0  Mon Aug 19 11:26:55:096 CDT 2024  Successfully loaded conversion table for ccsid: 37
JobCourier0  Mon Aug 19 11:26:55:096 CDT 2024  Sign-on completed.
JobCourier0  Mon Aug 19 11:26:55:097 CDT 2024  Disconnecting temporary connection for validating signon info.
JobCourier0  Mon Aug 19 11:26:55:099 CDT 2024  Service disconnected implementation:  as-signon
JobCourier0  Mon Aug 19 11:26:55:100 CDT 2024  Establishing connection to system: as-database
JobCourier0  Mon Aug 19 11:26:55:108 CDT 2024  Opening socket for service 4 to system...SYS01.repsrv.com port:446
JobCourier0  Mon Aug 19 11:26:55:113 CDT 2024  Getting socket login timeout is set:  true
JobCourier0  Mon Aug 19 11:26:55:113 CDT 2024  Getting so socket login timeout:  0
JobCourier0  Mon Aug 19 11:26:55:123 CDT 2024  Connect to socket: system 'SYS01.repsrv.com', port 446, login timeout 0 ms.
JobCourier0  Mon Aug 19 11:26:55:191 CDT 2024  Setting socket options...
JobCourier0  Mon Aug 19 11:26:55:192 CDT 2024  Socket properties:
JobCourier0  Mon Aug 19 11:26:55:192 CDT 2024      Remote address: SYS01.repsrv.com/10.4.18.90
JobCourier0  Mon Aug 19 11:26:55:193 CDT 2024      Remote port:  446
JobCourier0  Mon Aug 19 11:26:55:193 CDT 2024      Local address: /192.168.37.187
JobCourier0  Mon Aug 19 11:26:55:193 CDT 2024      Local port:  58604
JobCourier0  Mon Aug 19 11:26:55:193 CDT 2024      Keep alive:  false
JobCourier0  Mon Aug 19 11:26:55:194 CDT 2024      Receive buffer size:  65536
JobCourier0  Mon Aug 19 11:26:55:194 CDT 2024      Send buffer size:  64512
JobCourier0  Mon Aug 19 11:26:55:194 CDT 2024      So linger:  -1
JobCourier0  Mon Aug 19 11:26:55:194 CDT 2024      So timeout:  0
JobCourier0  Mon Aug 19 11:26:55:194 CDT 2024      TCP no delay:  false
JobCourier0  Mon Aug 19 11:26:55:194 CDT 2024  Starting an inet socket to as-database
JobCourier0  Mon Aug 19 11:26:55:194 CDT 2024  Checking for multiple Toolbox versions.
JobCourier0  Mon Aug 19 11:26:55:196 CDT 2024  Path of AS400 class:  file:/C:/temp/jt400/jt400.jar!/com/ibm/as400/access/AS400.class
JobCourier0  Mon Aug 19 11:26:55:197 CDT 2024  Path of loaded impl class:  file:/C:/temp/jt400/jt400.jar!/com/ibm/as400/access/SocketContainerInet.class
JobCourier0  Mon Aug 19 11:26:55:202 CDT 2024  Sending exchange random seeds request...
JobCourier0  Mon Aug 19 11:26:55:203 CDT 2024  Data stream sent (connID=2101871721) ...
00 00 00 1C 02 00 E0 04 00 00 00 00 00 00 00 00 
00 08 70 01 00 00 01 91 6B 76 85 62 
JobCourier0  Mon Aug 19 11:26:55:204 CDT 2024  Receiving exchange random seeds reply...
JobCourier0  Mon Aug 19 11:26:55:245 CDT 2024  Data stream data received (connID=2101871721) ...
00 15 D0 02 FF FF 00 0F 12 45 00 06 11 49 00 08 
00 05 11 3F 
JobCourier0  Mon Aug 19 11:26:55:246 CDT 2024  Data stream data received (connID=2101871721) ...
06 
JobCourier0  Mon Aug 19 11:26:55:247 CDT 2024  Failed to read all of the data stream.
java.lang.Throwable
	at com.ibm.as400.access.Trace.logData(Trace.java:767)
	at com.ibm.as400.access.Trace.log(Trace.java:827)
	at com.ibm.as400.access.DataStream.readAfterHeader(DataStream.java:258)
	at com.ibm.as400.access.AS400XChgRandSeedReplyDS.read(AS400XChgRandSeedReplyDS.java:63)
	at com.ibm.as400.access.AS400ImplRemote.getConnection(AS400ImplRemote.java:1596)
	at com.ibm.as400.access.AS400ImplRemote.connect(AS400ImplRemote.java:622)
	at com.ibm.as400.access.AS400.connectService(AS400.java:1669)
	at com.ibm.as400.access.AS400JDBCConnectionImpl.setProperties(AS400JDBCConnectionImpl.java:3547)
	at com.ibm.as400.access.AS400JDBCDriver.prepareConnection(AS400JDBCDriver.java:1540)
	at com.ibm.as400.access.AS400JDBCDriver.initializeConnection(AS400JDBCDriver.java:1374)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:511)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:316)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:289)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.tibco.pe.core.JDBCPool.getConnectionEntry(Unknown Source)
	at com.tibco.pe.core.JDBCPool.getConnectionEntry(Unknown Source)
	at com.tibco.pe.core.JDBCPoolManager.getConnectionEntry(Unknown Source)
	at com.tibco.plugin.jdbc.JDBCActivity.eval(Unknown Source)
	at com.tibco.pe.plugin.Activity.eval(Unknown Source)
	at com.tibco.pe.core.TaskImpl.eval(Unknown Source)
	at com.tibco.pe.core.Job.a(Unknown Source)
	at com.tibco.pe.core.Job.k(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.a(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.run(Unknown Source)
JobCourier0  Mon Aug 19 11:26:55:284 CDT 2024  Establishing connection failed:
com.ibm.as400.access.ConnectionDroppedException: Connection was dropped unexpectedly.
	at com.ibm.as400.access.DataStream.readAfterHeader(DataStream.java:259)
	at com.ibm.as400.access.AS400XChgRandSeedReplyDS.read(AS400XChgRandSeedReplyDS.java:63)
	at com.ibm.as400.access.AS400ImplRemote.getConnection(AS400ImplRemote.java:1596)
	at com.ibm.as400.access.AS400ImplRemote.connect(AS400ImplRemote.java:622)
	at com.ibm.as400.access.AS400.connectService(AS400.java:1669)
	at com.ibm.as400.access.AS400JDBCConnectionImpl.setProperties(AS400JDBCConnectionImpl.java:3547)
	at com.ibm.as400.access.AS400JDBCDriver.prepareConnection(AS400JDBCDriver.java:1540)
	at com.ibm.as400.access.AS400JDBCDriver.initializeConnection(AS400JDBCDriver.java:1374)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:511)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:316)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:289)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.tibco.pe.core.JDBCPool.getConnectionEntry(Unknown Source)
	at com.tibco.pe.core.JDBCPool.getConnectionEntry(Unknown Source)
	at com.tibco.pe.core.JDBCPoolManager.getConnectionEntry(Unknown Source)
	at com.tibco.plugin.jdbc.JDBCActivity.eval(Unknown Source)
	at com.tibco.pe.plugin.Activity.eval(Unknown Source)
	at com.tibco.pe.core.TaskImpl.eval(Unknown Source)
	at com.tibco.pe.core.Job.a(Unknown Source)
	at com.tibco.pe.core.Job.k(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.a(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.run(Unknown Source)
JobCourier0  Mon Aug 19 11:26:55:290 CDT 2024  as400: ConnectionImpl null (1194704028) : Throwing exception. Original exception: .com.ibm.as400.access.ConnectionDroppedException: Connection was dropped unexpectedly.
	at com.ibm.as400.access.DataStream.readAfterHeader(DataStream.java:259)
	at com.ibm.as400.access.AS400XChgRandSeedReplyDS.read(AS400XChgRandSeedReplyDS.java:63)
	at com.ibm.as400.access.AS400ImplRemote.getConnection(AS400ImplRemote.java:1596)
	at com.ibm.as400.access.AS400ImplRemote.connect(AS400ImplRemote.java:622)
	at com.ibm.as400.access.AS400.connectService(AS400.java:1669)
	at com.ibm.as400.access.AS400JDBCConnectionImpl.setProperties(AS400JDBCConnectionImpl.java:3547)
	at com.ibm.as400.access.AS400JDBCDriver.prepareConnection(AS400JDBCDriver.java:1540)
	at com.ibm.as400.access.AS400JDBCDriver.initializeConnection(AS400JDBCDriver.java:1374)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:511)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:316)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:289)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.tibco.pe.core.JDBCPool.getConnectionEntry(Unknown Source)
	at com.tibco.pe.core.JDBCPool.getConnectionEntry(Unknown Source)
	at com.tibco.pe.core.JDBCPoolManager.getConnectionEntry(Unknown Source)
	at com.tibco.plugin.jdbc.JDBCActivity.eval(Unknown Source)
	at com.tibco.pe.plugin.Activity.eval(Unknown Source)
	at com.tibco.pe.core.TaskImpl.eval(Unknown Source)
	at com.tibco.pe.core.Job.a(Unknown Source)
	at com.tibco.pe.core.Job.k(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.a(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.run(Unknown Source)

JobCourier0  Mon Aug 19 11:26:55:298 CDT 2024  as400: ConnectionImpl null (1194704028) : Throwing exception.  Actual exception: The application requester cannot establish the connection. (Connection was dropped unexpectedly.) sqlState: 08001 vendor code -99999.java.sql.SQLNonTransientConnectionException: The application requester cannot establish the connection. (Connection was dropped unexpectedly.)
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:877)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:605)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:563)
	at com.ibm.as400.access.AS400JDBCConnectionImpl.setProperties(AS400JDBCConnectionImpl.java:3560)
	at com.ibm.as400.access.AS400JDBCDriver.prepareConnection(AS400JDBCDriver.java:1540)
	at com.ibm.as400.access.AS400JDBCDriver.initializeConnection(AS400JDBCDriver.java:1374)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:511)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:316)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:289)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.tibco.pe.core.JDBCPool.getConnectionEntry(Unknown Source)
	at com.tibco.pe.core.JDBCPool.getConnectionEntry(Unknown Source)
	at com.tibco.pe.core.JDBCPoolManager.getConnectionEntry(Unknown Source)
	at com.tibco.plugin.jdbc.JDBCActivity.eval(Unknown Source)
	at com.tibco.pe.plugin.Activity.eval(Unknown Source)
	at com.tibco.pe.core.TaskImpl.eval(Unknown Source)
	at com.tibco.pe.core.Job.a(Unknown Source)
	at com.tibco.pe.core.Job.k(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.a(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.run(Unknown Source)

JobCourier0  Mon Aug 19 11:26:55:300 CDT 2024  as400: ConnectionImpl null (1194704028) : Calling DriverManager.getDrivers.
JobCourier0  Mon Aug 19 11:26:55:305 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver AS/400 Toolbox for Java JDBC Driver:1799492991 class:class com.ibm.as400.access.AS400JDBCDriver.
JobCourier0  Mon Aug 19 11:26:55:306 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver SQLServerDriver:1:451794011 class:class com.microsoft.sqlserver.jdbc.SQLServerDriver.
JobCourier0  Mon Aug 19 11:26:55:306 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver com.ibm.db2.jcc.DB2Driver@455183ad:1162970029 class:class com.ibm.db2.jcc.DB2Driver.
JobCourier0  Mon Aug 19 11:26:55:306 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver oracle.jdbc.OracleDriver@7032aa6b:1882368619 class:class oracle.jdbc.OracleDriver.
JobCourier0  Mon Aug 19 11:26:55:306 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver org.postgresql.Driver@32fc6a38:855403064 class:class org.postgresql.Driver.
JobCourier0  Mon Aug 19 11:26:55:306 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.db2.DB2Driver@54697e9:88512489 class:class tibcosoftwareinc.jdbc.db2.DB2Driver.
JobCourier0  Mon Aug 19 11:26:55:306 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.greenplum.GreenplumDriver@5e5ffe68:1583349352 class:class tibcosoftwareinc.jdbc.greenplum.GreenplumDriver.
JobCourier0  Mon Aug 19 11:26:55:307 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.hive.HiveDriver@31a423e9:832840681 class:class tibcosoftwareinc.jdbc.hive.HiveDriver.
JobCourier0  Mon Aug 19 11:26:55:307 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.informix.InformixDriver@68cbbc8:109886408 class:class tibcosoftwareinc.jdbc.informix.InformixDriver.
JobCourier0  Mon Aug 19 11:26:55:307 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.mysql.MySQLDriver@3d672c07:1030171655 class:class tibcosoftwareinc.jdbc.mysql.MySQLDriver.
JobCourier0  Mon Aug 19 11:26:55:307 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.oracle.OracleDriver@223019eb:573577707 class:class tibcosoftwareinc.jdbc.oracle.OracleDriver.
JobCourier0  Mon Aug 19 11:26:55:307 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.redshift.RedshiftDriver@1b30913d:456167741 class:class tibcosoftwareinc.jdbc.redshift.RedshiftDriver.
JobCourier0  Mon Aug 19 11:26:55:308 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.sforce.SForceDriver@35344932:892619058 class:class tibcosoftwareinc.jdbc.sforce.SForceDriver.
JobCourier0  Mon Aug 19 11:26:55:308 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.sqlserver.SQLServerDriver@2d1061a6:756048294 class:class tibcosoftwareinc.jdbc.sqlserver.SQLServerDriver.
JobCourier0  Mon Aug 19 11:26:55:308 CDT 2024  as400: ConnectionImpl null (1194704028) : ..found driver tibcosoftwareinc.jdbc.sybase.SybaseDriver@5bb783ce:1538753486 class:class tibcosoftwareinc.jdbc.sybase.SybaseDriver.
JobCourier0  Mon Aug 19 11:26:55:308 CDT 2024  as400: ConnectionImpl null (1194704028) : done looking at drivers.
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:880 CDT 2024  CredentialVault.disposeOfCredential called
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:882 CDT 2024  CredentialVault.disposeOfCredential called
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:882 CDT 2024  Finalize method for AS400 implementation invoked.
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:882 CDT 2024  Disconnecting all services implementation...
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:882 CDT 2024  Service disconnected implementation:  as-file
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:882 CDT 2024  Service disconnected implementation:  as-netprt
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:882 CDT 2024  Service disconnected implementation:  as-dtaq
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:882 CDT 2024  Service disconnected implementation:  as-rmtcmd
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:883 CDT 2024  Service disconnected implementation:  as-database
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:883 CDT 2024  Service disconnected implementation:  as-ddm
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:883 CDT 2024  Service disconnected implementation:  as-central
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:884 CDT 2024  Service disconnected implementation:  as-signon
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:884 CDT 2024  All services disconnected implementation.
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:884 CDT 2024  CredentialVault.disposeOfCredential called
Thread[Finalizer,8,system]  Mon Aug 19 11:26:55:885 CDT 2024  CredentialVault.disposeOfCredential called
2024 Aug 19 11:26:56:889 GMT -0500 BW.RepublicSystemServicesV2_US24911_local Error [BW-Plugin] BW-JDBC-100039 Job-24000 Error in [RepublicSystemServices/InfoPro/SystemInterfaces/Customer/Enroll Customer.process/Enroll ePortal Customer]
"JDBC Connection Login timed out"
	at com.tibco.plugin.jdbc.JDBCActivity.eval(Unknown Source)
	at com.tibco.pe.plugin.Activity.eval(Unknown Source)
	at com.tibco.pe.core.TaskImpl.eval(Unknown Source)
	at com.tibco.pe.core.Job.a(Unknown Source)
	at com.tibco.pe.core.Job.k(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.a(Unknown Source)
	at com.tibco.pe.core.JobDispatcher$JobCourier.run(Unknown Source)
<?xml version="1.0" encoding="UTF-8"?>

<Data>
    <ns0:LoginTimedOutException xmlns:ns0="http://schemas.tibco.com/bw/plugins/jdbc/5.0/jdbcExceptions">
        <msg>"JDBC Connection Login timed out"</msg>
        <msgCode>BW-JDBC-100039</msgCode>
    </ns0:LoginTimedOutException>
</Data> 
"2024 Aug 19 11:26:57:218 CDT   Activity Error, BW-JDBC-100039 Job-24000 Error in [RepublicSystemServices/InfoPro/SystemInterfaces/Customer/Enroll Customer.process/Enroll ePortal Customer]
"JDBC Connection Login timed out"
 
"

**Comment by jeber-ibm** [comment]
The trace shows you are connecting to port 446, the DRDA port.  The JTOpen driver does not use a DRDA protocol for JDBC access and will not connect to port 446.  The default port for the Database host server is 8471
