### ISSUE TITLE
ProgramCall results in Read timed out

### ISSUE THREAD

**Issue by Bratmaxxe119** [IBM/JTOpen#225]
Hi,

i am currently using jt400.jar (11.1). After a specific time (maybe 10-20 minutes), program calls do not work anymore and the following exception occurs:

`Mi Dez 18 09:33:58:713 MEZ 2024  run(): Caught IOException:
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at com.ibm.as400.access.DataStream.readFromStream(DataStream.java:54)
	at com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:61)
	at com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:359)
	at java.lang.Thread.run(Unknown Source)
Mi Dez 18 09:33:58:714 MEZ 2024  receive(): Read daemon exception:
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at com.ibm.as400.access.DataStream.readFromStream(DataStream.java:54)
	at com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:61)
	at com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:359)
	at java.lang.Thread.run(Unknown Source)
Mi Dez 18 09:33:58:715 MEZ 2024  Lost connection to remote command server:
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at com.ibm.as400.access.DataStream.readFromStream(DataStream.java:54)
	at com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:61)
	at com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:359)
	at java.lang.Thread.run(Unknown Source)
Mi Dez 18 09:33:58:716 MEZ 2024  Send end job data stream failed:
java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at com.ibm.as400.access.DataStream.write(DataStream.java:338)
	at com.ibm.as400.access.AS400EndJobDS.write(AS400EndJobDS.java:56)
	at com.ibm.as400.access.AS400ThreadedServer.forceDisconnect(AS400ThreadedServer.java:246)
	at com.ibm.as400.access.AS400ImplRemote.disconnectServer(AS400ImplRemote.java:727)
	at com.ibm.as400.access.RemoteCommandImplRemote.disconnectServer(RemoteCommandImplRemote.java:834)
	at com.ibm.as400.access.RemoteCommandImplRemote.runProgramOffThread(RemoteCommandImplRemote.java:608)
	at com.ibm.as400.access.RemoteCommandImplRemote.runProgram(RemoteCommandImplRemote.java:532)
	at com.ibm.as400.access.ProgramCall.run(ProgramCall.java:792)
Mi Dez 18 09:33:58:719 MEZ 2024  forceDisconnect calling readDaemon_.interrupt
`

I checked the state of the as400 object and connection, which is still alive.
How can i prevent this error?

Br,
Bratmaxxe

**Comment by Bratmaxxe119** [comment]
Added example

[PGM_Call.txt](https://github.com/user-attachments/files/18178385/PGM_Call.txt)

**Comment by nadiramra** [comment]
If connection is ended on server side, you will get this error, even if you check via toolbox if connection is alive because the old implementation of the isAlive method did not check the read-side of the connection.  Get the newest release which corrects that problem.  In addition, there is a new method to keep connections alive, setStayAlive() on the AS400 class.

**Comment by Bratmaxxe119** [comment]
Hi,

many thanks for your advice.
