### ISSUE TITLE
SQLException: Internal driver error occurs since JTOpen version 20.0.0

### ISSUE THREAD

**Issue by MNeuling** [IBM/JTOpen#97]
The error occurs while persisting a Hibernate entity. It doesn't occur with JTOpen version 11.2 and before.
It happens with Hibernate 5 and 6.

### Stacktrace with Hibernate 5:
```
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not extract ResultSet
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:917)
        at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:891)
        at sun.reflect.GeneratedMethodAccessor1248.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.as.jpa.container.EntityManagerUnwrappedTargetInvocationHandler.invoke(EntityManagerUnwrappedTargetInvocationHandler.java:61)
        at com.sun.proxy.$Proxy297.merge(Unknown Source)
        at com.asap.dragon.server.ejb.AbstractPersistenceSessionBean.persist(AbstractPersistenceSessionBean.java:436)
        at com.asap.dragon.server.ejb.AbstractPersistenceSessionBean.persist(AbstractPersistenceSessionBean.java:425)
        at com.asap.dragon.server.ejb.AbstractPersistenceSessionBean.persist(AbstractPersistenceSessionBean.java:414)
        at com.asap.dragon.server.ejb.AbstractPersistenceSessionBean.saveAndLoad(AbstractPersistenceSessionBean.java:208)
        at com.asap.dragon.server.ejb.AbstractPersistenceSessionBean.save(AbstractPersistenceSessionBean.java:123)
        at com.asap.dragon.server.ejb.AbstractPersistenceSessionBean.save(AbstractPersistenceSessionBean.java:105)
        at sun.reflect.GeneratedMethodAccessor3025.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
        at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79)
        at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89)
        at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102)
        at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:49)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:201)
        ... 132 more
Caused by: org.hibernate.exception.GenericJDBCException: could not extract ResultSet
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:69)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2265)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2028)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1990)
        at org.hibernate.loader.Loader.doQuery(Loader.java:949)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:321)
        at org.hibernate.loader.Loader.loadEntity(Loader.java:2379)
        at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:64)
        at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:54)
        at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4290)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:604)
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:572)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:226)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:350)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:127)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:93)
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1277)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1265)
        at org.hibernate.internal.SessionImpl.access$2000(SessionImpl.java:208)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2901)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2875)
        at org.hibernate.internal.SessionImpl.get(SessionImpl.java:1102)
        at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:322)
        at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:188)
        at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:72)
        at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:905)
        ... 171 more
Caused by: java.sql.SQLException: Internal driver error. (class java.lang.InterruptedException)
        at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:985)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:610)
        at com.ibm.as400.access.JDError.throwSQLException(JDError.java:568)
        at com.ibm.as400.access.AS400JDBCConnectionImpl.sendAndReceive(AS400JDBCConnectionImpl.java:3167)
        at com.ibm.as400.access.AS400JDBCStatement.commonExecute(AS400JDBCStatement.java:975)
        at com.ibm.as400.access.AS400JDBCPreparedStatementImpl.executeQuery(AS400JDBCPreparedStatementImpl.java:1794)
        at org.jboss.jca.adapters.jdbc.CachedPreparedStatement.executeQuery(CachedPreparedStatement.java:113)
        at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:504)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
        ... 197 more
Caused by: java.lang.InterruptedException
        at java.lang.Object.waitImpl(Native Method)
        at java.lang.Object.wait(Object.java:248)
        at java.lang.Object.wait(Object.java:187)
        at com.ibm.as400.access.AS400ThreadedServer.receive(AS400ThreadedServer.java:341)
        at com.ibm.as400.access.AS400ThreadedServer.sendAndReceive(AS400ThreadedServer.java:494)
        at com.ibm.as400.access.AS400JDBCConnectionImpl.sendAndReceive(AS400JDBCConnectionImpl.java:3118)
        ... 202 more
```

**Comment by jeber-ibm** [comment]
This is odd.  It looks like something is interrupting the ThreadedServer thread.  Perhaps a toolbox trace would provide more information.  Can you recreate and provide a toolbox trace with the all option? 

Details about toolbox trace can be found at https://www.ibm.com/support/pages/all-one-toolbox-tracing-guide.
